window.onload = function(){
	var motsClefs = [
		'Aast',
'Abbeville',
'Ablis',
'Achères (Yvelines)',
'Acqueville',
'Agde',
'Agel',
'Agen',
'Aigues-Mortes',
'Ainay-le-Château',
'Aix-en-Provence',
'Aix-les-Bains',
'Aizenay',
'Ajaccio',
'Albert (Somme)',
'Albertville',
'Albi',
'Albigny-sur-Saône',
'Alençon',
'Alfortville',
'Allemanche-Launay-et-Soyer',
'Alès',
'Amboise',
'Ambérieu-en-Bugey',
'Amiens',
'Ancenis',
'Ancretiéville-Saint-Victor',
'Andilly',
'Andilly-en-Bassigny',
'Anet',
'Angers',
'Anglesqueville-l\'Esneval',
'Angoulême',
'Annecy',
'Annemasse',
'Annonay',
'Antibes',
'Antony',
'Apt',
'Arcachon',
'Arconsat',
'Ardes',
'Argenteuil',
'Arles',
'Armentières',
'Arras',
'Arudy',
'Asnières-sur-Seine',
'Astaffort',
'Aubagne',
'Aubière',
'Aubrives',
'Aubusson',
'Auch',
'Aulnay-sous-Bois',
'Auray',
'Aurillac',
'Auriol (Bouches-du-Rhône)',
'Autun',
'Auvers-sur-Oise',
'Auxerre',
'Avignon',
'Avranches',
'Avril-sur-Loire',
'Ax-les-Thermes',
'Aydat',
'Aydius',
'Azay-le-Rideau',
'Bailleul',
'Bar-le-Duc',
'Bar-sur-Aube',
'Baratier',
'Barbizon',
'Barcelonnette',
'Barneville-Carteret',
'Basse-Terre',
'Bastia',
'Batz-sur-Mer',
'Bavay',
'Bayeux',
'Bayonne',
'Beaumont-Hague',
'Beaune',
'Beauvais',
'Bégard',
'Belfort',
'Bellerive-sur-Allier',
'Belley',
'Berck',
'Bergerac',
'Bergues',
'Bernay',
'Berthen',
'Besançon',
'Bessoncourt',
'Béthune',
'Beuvry',
'Beynost',
'Bèze',
'Béziers',
'Biarritz',
'Billiat',
'Billom',
'Billy (Allier)',
'Binas',
'Biot (Alpes-Maritimes)',
'Biscarrosse',
'Bischwiller',
'Blagnac',
'Blain',
'Blandy-les-Tours',
'Blois',
'Bobigny',
'Boissy-Saint-Léger',
'Bonchamp-lès-Laval',
'Bondy',
'Bonifacio',
'Bonnat',
'Bonnières-sur-Seine',
'Bordeaux',
'Bordeaux-Saint-Clair',
'Bort-les-Orgues',
'Bouère',
'Bougival',
'Bouilly (Aube)',
'Boulogne-Billancourt',
'Boulogne-sur-Mer',
'Bourdeau (Savoie)',
'Bourg-en-Bresse',
'Bourg-la-Reine',
'Bourges',
'Le Bourget',
'Bourogne',
'Boussières',
'Bouvines',
'Bram',
'Brancion',
'Brassempouy',
'Bray-Dunes',
'Brebotte',
'Bressuire',
'Brest',
'Breuilpont',
'Briançon',
'Bricquebec',
'Brie-Comte-Robert',
'Brié-et-Angonnes',
'Briennon',
'Brioude',
'Brive-la-Gaillarde',
'Bron',
'Bruguières',
'Buffard',
'Bugarach',
'Busserolles',
'Cabestany',
'Cachan',
'Caen',
'Cagnes-sur-Mer',
'Cahors',
'Cailloux-sur-Fontaines',
'Calais',
'Caluire-et-Cuire',
'Calvi',
'Camaret-sur-Mer',
'Cambrai',
'Cangey',
'Cannes',
'Carcassonne',
'Carentan',
'Carhaix-Plouguer',
'Carmaux',
'Carnac',
'Carpentras',
'Carrières-sous-Poissy',
'Castelginest',
'Castellane',
'Castellet-lès-Sausses',
'Castelmoron-d\'Albret',
'Castres',
'Cauchy-à-la-Tour',
'Caudry',
'Cayenne',
'Cébazat',
'Cergy',
'Cestas',
'Chabeuil',
'Challans',
'Chalon-sur-Saône',
'Châlons-en-Champagne',
'Chambéry',
'Chamonix',
'Champagne-au-Mont-d\'Or',
'Champagney',
'Champagnier',
'Champagnole',
'Champéon',
'Chantilly',
'Charbonnières-les-Bains',
'Charenton-le-Pont',
'Charleville-Mézières',
'Charly (métropole de Lyon)',
'Chartres',
'Chasse-sur-Rhône',
'Chassieu',
'Châteaubriant',
'Châteaudun',
'Châteaulin',
'Châteauneuf-Grasse',
'Châteauroux',
'Châtelaillon-Plage',
'Châtellerault',
'Chatou',
'Chaumont (Haute-Marne)',
'Chaumont-sur-Loire',
'Chelles',
'Chemillé-en-Anjou',
'Chenonceaux',
'Cherbourg-Octeville',
'Cherves-Richemont',
'Chessy (Seine-et-Marne)',
'Chevreuse',
'Chinon',
'Cholet',
'Château-Chinon',
'Château-Thierry',
'Châteaufort (Yvelines)',
'Châteauneuf-sur-Loire',
'Châtenay-Malabry',
'Chédigny',
'Ciboure',
'Cierrey',
'Cigogné',
'Cintegabelle',
'Clamart',
'Clayes',
'Clermont (Oise)',
'Clermont-Ferrand',
'Clichy',
'Clichy-sous-Bois',
'Clisson',
'Cluny',
'Cognac',
'Coise',
'Colleville-Montgomery',
'Collias',
'Collioure',
'Collonges-au-Mont-d\'Or',
'Colmar',
'Colombes',
'Colombier-Saugnieu',
'Colomiers',
'Combloux',
'Combon',
'Commercy',
'Compiègne',
'Conchy-les-Pots',
'Condom',
'Conflans-Sainte-Honorine',
'Confolens',
'Corbas',
'Corbon (Orne)',
'Cordon',
'Corrèze (commune)',
'Corte',
'Courbevoie',
'Courrières',
'Courçais',
'Coutances',
'Couzon-au-Mont-d\'Or',
'Craponne',
'Créteil',
'Criquetot-l\'Esneval',
'Crossac',
'Cublize',
'Cuges-les-Pins',
'Curis-au-Mont-d\'Or',
'Cusset',
'Dannemarie (Haut-Rhin)',
'Dardilly',
'Dax',
'Deauville',
'Décines-Charpieu',
'Delle',
'Denney',
'Descartes (Indre-et-Loire)',
'Deûlémont',
'Devesset',
'Die',
'Dieppe',
'Digne-les-Bains',
'Dijon',
'Dinan',
'Dol-de-Bretagne',
'Dole',
'Dombasle-sur-Meurthe',
'Domfessel',
'Domrémy',
'Douai',
'Doullens',
'Dourdan',
'Douvres-la-Délivrande',
'Draguignan',
'Drancy',
'Dreux',
'Drusenheim',
'Dunkerque',
'Écully',
'Égletons',
'Élancourt',
'Éloise',
'Épernay',
'Épinac',
'Épinal',
'Épinay-sur-Seine',
'Épône',
'Ermenonville',
'Erquinghem-le-Sec',
'Erquy',
'Espelette',
'Estagel',
'Étretat',
'Évian-les-Bains',
'Évreux',
'Évry-Courcouronnes',
'Eysines',
'Faches-Thumesnil',
'Falaise (Calvados)',
'Farnay',
'Fécamp',
'Fêche-l\'Église',
'Felleries',
'Ferney-Voltaire',
'Feurs',
'Feyzin',
'Figeac',
'Firminy',
'Flavigny-sur-Moselle',
'Fleurieu-sur-Saône',
'Floirac (Gironde)',
'Florac',
'Flottemanville-Hague',
'Foisches',
'Foix',
'Fongueusemare',
'Fontainebleau',
'Fontaines-Saint-Martin',
'Fontaines-sur-Saône',
'Fontenay-le-Comte',
'Fontenay-le-Fleury',
'Fontès',
'Forbach',
'Forcalquier',
'Fort-de-France',
'Fos-sur-Mer',
'Fougères',
'Fouras',
'Fournels',
'Frais (Territoire de Belfort)',
'Francheville (métropole de Lyon)',
'Freneuse (Yvelines)',
'Fréjus',
'Fumay',
'Gagny',
'Galgan',
'Gambsheim',
'Gap',
'Garges-lès-Gonesse',
'Garnat-sur-Engièvre',
'Gémenos',
'Genas',
'Genay (métropole de Lyon)',
'Gentilly',
'Gernelle',
'Gevrey-Chambertin',
'Gex',
'Givet',
'Givors',
'Gleizé',
'Gragnague',
'Grand (Vosges)',
'Granville',
'Grasse',
'Graulhet',
'Gravelines',
'Gray',
'Grenoble',
'Grigny (métropole de Lyon)',
'Grosne',
'Guémené-Penfao',
'Guérande',
'Guéret',
'Guingamp',
'Guipavas',
'Guise',
'Guyancourt',
'Hagetmau',
'Haguenau',
'Hambach',
'Hargnies',
'Hazebrouck',
'Héauville',
'Helleville',
'Hénanbihen',
'Hendaye',
'Hennebont',
'Héricourt',
'Hettange-Grande',
'Heuqueville',
'Heyrieux',
'Hirel',
'Homécourt',
'Honfleur',
'Houilles',
'Houlgate',
'Irigny',
'Issenheim',
'Issoire',
'Issou',
'Issy-les-Moulineaux',
'Istres',
'Ivry-sur-Seine',
'Izernore',
'Jacou',
'Jallans',
'Jargeau',
'Jonage',
'Jonzac',
'Jouy-en-Josas',
'Jublains',
'Juvisy-sur-Orge',
'Kourou',
'L\'Haÿ-les-Roses',
'L\'Union',
'L\'Île-Rousse',
'La Balme-de-Sillingy',
'La Baule-Escoublac',
'La Boisse',
'La Bonneville-sur-Iton',
'La Celette',
'La Chaise-Dieu',
'La Chapelle-Rablais',
'La Fare-les-Oliviers',
'La Féclaz',
'La Londe-les-Maures',
'La Motte-Servolex',
'La Mulatière',
'La Roche-Guyon',
'La Roche-sur-Yon',
'La Rochelle',
'La Tour-de-Salvagny',
'La Trimouille',
'La Trinité-sur-Mer',
'La Villeneuve-en-Chevrie',
'La Voulte-sur-Rhône',
'Labrit',
'Lagny-sur-Marne',
'Laguiole',
'Lalouvesc',
'Lambersart',
'Landerneau',
'Landivisiau',
'Langeais',
'Langres',
'Languidic',
'Lannilis',
'Lannion',
'Lans-en-Vercors',
'Laon',
'Lapalisse',
'Larajasse',
'Largentière',
'Laval (Mayenne)',
'Le Cannet',
'Le Cellier',
'Le Chambon-sur-Lignon',
'Le Chesnay-Rocquencourt',
'Le Creusot',
'Le Croisic',
'Le Drennec',
'Le Faouët (Morbihan)',
'Le Havre',
'Le Mans',
'Le Mené',
'Le Mée-sur-Seine',
'Le Neubourg',
'Le Pecq',
'Le Perreux-sur-Marne',
'Le Perrier',
'Le Perthus',
'Le Port (La Réunion)',
'Le Pouliguen',
'Le Puy-en-Velay',
'Le Quesnoy',
'Le Raincy',
'Le Rozel',
'Le Tartre-Gaudran',
'Le Tilleul',
'Le Touquet-Paris-Plage',
'Le Tréport',
'Le Versoud',
'Le Vigan (Gard)',
'Le Vésinet',
'Lebetain',
'Lectoure',
'Lens',
'Lepuix-Neuf',
'Les Andelys',
'Les Baux-de-Provence',
'Les Clayes-sous-Bois',
'Les Eyzies-de-Tayac',
'Les Loges-en-Josas',
'Les Mathes',
'Les Mureaux',
'Les Sables-d\'Olonne',
'Lesme',
'Levallois-Perret',
'Lezigneux',
'Libourne',
'Liévin',
'Lille',
'Limay',
'Limeil-Brévannes',
'Limoges',
'Limonest',
'Limoux',
'Lion-sur-Mer',
'Lisieux',
'Lissieu',
'Loiron-Ruillé',
'Longwy',
'Lons-le-Saunier',
'Lorgues',
'Lorient',
'Lorris',
'Loudéac',
'Louhossoa',
'Loulay',
'Loupia',
'Lourdes',
'Luc-sur-Mer',
'Luçon (Vendée)',
'Lunel',
'Lunéville',
'Lure',
'Lussault-sur-Loire',
'Lyon',
'Mackenheim',
'Mâcon',
'Maisons-Alfort',
'Maisons-Laffitte',
'Mamoudzou',
'Mantes-la-Jolie',
'Mantes-la-Ville',
'Marcy-l\'Étoile',
'Marennes-Hiers-Brouage',
'Mareuil-sur-Cher',
'Marlhes',
'Marly-le-Roi',
'Marquette-lez-Lille',
'Marray',
'Marseille',
'Martigues',
'Maubeuge',
'Mauges-sur-Loire',
'Maurepas (Yvelines)',
'Mauriac (Cantal)',
'Mayrac',
'Mazaugues',
'Meaux',
'Melun',
'Mende',
'Ménerbes',
'Menouville',
'Menton (Alpes-Maritimes)',
'Mérens-les-Vals',
'Merlimont',
'Metz',
'Meudon',
'Meyzieu',
'Millau',
'Milly-la-Forêt',
'Mimizan',
'Mions',
'Mirande',
'Mirepoix',
'Miribel (Ain)',
'Moissac',
'Moisson (Yvelines)',
'Mont-Dauphin',
'Mont-de-Marsan',
'Mont-Dore',
'Montanay',
'Montargis',
'Montastruc-la-Conseillère',
'Montauban',
'Montbard',
'Montbéliard',
'Montceau-les-Mines',
'Montcy-Notre-Dame',
'Montebourg',
'Montélimar',
'Montesson',
'Montfort-l\'Amaury',
'Montivilliers',
'Montluel',
'Montluçon',
'Montmédy',
'Montpellier',
'Montpeyroux',
'Montredon-Labessonnié',
'Montreuil',
'Montreuil (Pas-de-Calais)',
'Montreux-Château',
'Montreux-Vieux',
'Montrottier',
'Montsoreau',
'Moret-sur-Loing',
'Morlaix',
'Morteau',
'Moulins',
'Mousseaux-sur-Seine',
'Moûtiers',
'Mulhouse',
'Munster (Moselle)',
'Murat (Saint-Médard La Rochette)',
'Muret',
'Murol',
'Nancy',
'Nanterre',
'Nantes',
'Nantua',
'Narbonne',
'Nérac',
'Neuf-Berquin',
'Neuf-Brisach',
'Neuilly-sur-Marne',
'Neuilly-sur-Seine',
'Neuville-sur-Saône',
'Nevers',
'Neyron',
'Nice',
'Nîmes',
'Niort',
'Nogent (Haute-Marne)',
'Nogent-le-Rotrou',
'Nogent-sur-Marne',
'Nogent-sur-Seine',
'Noirétable',
'Noisy-le-Roi',
'Nontron',
'Nonville (Seine-et-Marne)',
'Novillard',
'Noyon',
'Nozay (Essonne)',
'Nyons',
'Octeville-sur-Mer',
'Onet-le-Château',
'Opio',
'Oradour-sur-Glane',
'Orange (ville)',
'Orcines',
'Orcival',
'Orléans',
'Orly',
'Ornans',
'Osny',
'Osse-en-Aspe',
'Oullins',
'Ounans',
'Oyonnax',
'Ozoir-la-Ferrière',
'Paladru',
'Pamiers',
'Papeete',
'Paray-le-Monial',
'Parigny-les-Vaux',
'Paris',
'Paron',
'Parthenay',
'Pau',
'Paulnay',
'Périgueux',
'Péronne',
'Perpezat',
'Perpignan',
'Perros-Guirec',
'Petit-Croix',
'Peyrus',
'Pierre-Bénite',
'Pierrefiques',
'Pithiviers',
'Piégut-Pluviers',
'Plaisir (Yvelines)',
'Plateau d\'Hauteville',
'Plédéliac',
'Plénée-Jugon',
'Pléneuf-Val-André',
'Pleyben',
'Plomodiern',
'Plonévez-Porzay',
'Plouarzel',
'Plougastel-Daoulas',
'Pointe-à-Pitre',
'Poissy',
'Poitiers',
'Poleymieux-au-Mont-d\'Or',
'Pomayrols',
'Pommeret',
'Pons',
'Pont-l\'Évêque',
'Pont-Aven',
'Pont-de-Roide',
'Pont-de-Veyle',
'Pont-du-Château',
'Pontarlier',
'Pontivy',
'Pontoise',
'Pornichet',
'Port-Louis (Morbihan)',
'Porte des Pierres Dorées',
'Pralognan-la-Vanoise',
'Prat',
'Preuschdorf',
'Prey',
'Privas',
'Provins',
'Puiseaux',
'Pujaudran',
'Pusignan',
'Quiberon',
'Quimper',
'Quincieux',
'Quissac (Gard)',
'Rambouillet',
'Réchésy',
'Redon',
'Reims',
'Rennemoulin',
'Rennes',
'Rethel',
'Retonfey',
'Ribeauvillé',
'Rillieux-la-Pape',
'Riom',
'Rioz',
'Ris-Orangis',
'Risoul',
'Roanne',
'Rocamadour',
'Rochechouart',
'Rochefort',
'Rochetaillée-sur-Saône',
'Rocroi',
'Rodez',
'Rognac',
'Rohrwiller',
'Roissy-en-France',
'Rolleboise',
'Romainville',
'Romans-sur-Isère',
'Romenay',
'Romilly-sur-Seine',
'Roppe',
'Roquetoire',
'Roquevaire',
'Rosny-sur-Seine',
'Roubaix',
'Rouen',
'Roumare',
'Roussillon (Isère)',
'Royan',
'Rungis',
'Saint-Agathon',
'Saint-Amand-Montrond',
'Saint-André-lez-Lille',
'Saint-Austremoine',
'Saint-Bertrand-de-Comminges',
'Saint-Bonnet-de-Mure',
'Saint-Brieuc',
'Saint-Chamas',
'Saint-Chamond',
'Saint-Christophe-du-Foc',
'Saint-Claude-de-Diray',
'Saint-Cloud',
'Saint-Cyr-au-Mont-d\'Or',
'Saint-Cyr-l\'École',
'Saint-Denis (La Réunion)',
'Saint-Denis (Seine-Saint-Denis)',
'Saint-Didier-au-Mont-d\'Or',
'Saint-Dié-des-Vosges',
'Saint-Domineuc',
'Saint-Égrève',
'Saint-Estèphe',
'Saint-Étienne',
'Saint-Étienne-du-Rouvray',
'Saint-Flour',
'Saint-Fons',
'Saint-Gaudens',
'Saint-Genest-Lerpt',
'Saint-Genis-Laval',
'Saint-Genis-les-Ollières',
'Saint-Germain-au-Mont-d\'Or',
'Saint-Germain-en-Laye',
'Saint-Gilles-Croix-de-Vie',
'Saint-Girons',
'Saint-Gouéno',
'Saint-Haon-le-Vieux',
'Saint-Hilaire-de-Riez',
'Saint-Hilaire-du-Rosier',
'Saint-Jacut-du-Mené',
'Saint-Jean-d\'Angély',
'Saint-Jean-de-Luz',
'Saint-Jory',
'Saint-Julien-en-Genevois',
'Saint-Just-d\'Avray',
'Saint-Laurent-du-Pape',
'Saint-Lyé-la-Forêt',
'Saint-Léonard-de-Noblat',
'Saint-Lô',
'Saint-Malo',
'Saint-Mandé',
'Saint-Martin-d\'Ardèche',
'Saint-Martin-d\'Uriage',
'Saint-Martin-de-Queyrières',
'Saint-Martin-de-Ré',
'Saint-Martin-du-Bec',
'Saint-Maur-des-Fossés',
'Saint-Maurice-de-Beynost',
'Saint-Maurice-l\'Exil',
'Saint-Maximin-la-Sainte-Baume',
'Saint-Nazaire',
'Saint-Nectaire',
'Saint-Omer (Pas-de-Calais)',
'Saint-Ouen-sur-Seine',
'Saint-Paul-lès-Romans',
'Saint-Pierre (La Réunion)',
'Saint-Pierre (Martinique)',
'Saint-Pol-de-Léon',
'Saint-Priest',
'Saint-Quentin',
'Saint-Quentin-en-Yvelines',
'Saint-Quentin-sur-Indrois',
'Saint-Rémy-de-Provence',
'Saint-Romain-au-Mont-d\'Or',
'Saint-Romain-en-Gal',
'Saint-Romain-le-Puy',
'Saint-Rémy-lès-Chevreuse',
'Saint-Saturnin',
'Saint-Symphorien-sur-Coise',
'Saint-Tropez',
'Saint-Vaast-la-Hougue',
'Saint-Victor-sur-Rhins',
'Saint-Vougay',
'Saint-Zacharie (Var)',
'Sainte-Croix-Hague',
'Sainte-Cécile-les-Vignes',
'Sainte-Eulalie (Gironde)',
'Sainte-Foy-lès-Lyon',
'Sainte-Geneviève-des-Bois (Essonne)',
'Sainte-Luce (Martinique)',
'Sainte-Marie-de-Ré',
'Sainte-Mère-Église',
'Sainte-Pazanne',
'Saintes',
'Salazie',
'Salies-de-Béarn',
'Samois-sur-Seine',
'Sanary-sur-Mer',
'Saran',
'Sarlat-la-Canéda',
'Sarreguemines',
'Sartène',
'Sartrouville',
'Sathonay-Camp',
'Sathonay-Village',
'Saulieu',
'Saulnot',
'Saumur',
'Sauve',
'Sauveterre-de-Béarn',
'Savigny-sur-Orge',
'Savouges',
'Sceaux (Hauts-de-Seine)',
'Schiltigheim',
'Sebourg',
'Seclin',
'Sedan',
'Semur-en-Vallon',
'Senlis',
'Sens (Yonne)',
'Serres-Castet',
'Sète',
'Sevelinges',
'Sèvres',
'Sézanne',
'Sillingy',
'Siouville-Hague',
'Sochaux',
'Soissons',
'Solaize',
'Sommières',
'Sorbiers',
'Sorgues',
'Sotteville-lès-Rouen',
'Soulac-sur-Mer',
'Strasbourg',
'Sucy-en-Brie',
'Sully (Saône-et-Loire)',
'Sundhouse',
'Suresnes',
'Surgères',
'Talence',
'Tancua',
'Tarascon-sur-Ariège',
'Tarbes',
'Tassin-la-Demi-Lune',
'Tavaux',
'Teurthéville-Hague',
'Theizé',
'Thiers (ville)',
'Thil (Ain)',
'Thionville',
'Thomery',
'Thonon-les-Bains',
'Thorigny-sur-le-Mignon',
'Thérouanne',
'Tigery',
'Tinténiac',
'Tomblaine',
'Tonnay-Charente',
'Tonnerre (Yonne)',
'Torcy',
'Toul',
'Toulon',
'Toulouse',
'Tourcoing',
'Tournefeuille',
'Tournon (Savoie)',
'Tournon-sur-Rhône',
'Tournus',
'Tours',
'Toussus-le-Noble',
'Tramoyes',
'Trappes',
'Trédaniel',
'Trégomar',
'Treigny',
'Treize-Septiers',
'Trélévern',
'Tremblay-en-France',
'Troyes',
'Tulle',
'Turretot',
'Ussel',
'Uzès',
'Val d\'Oingt',
'Valaire',
'Valbonne',
'Valdahon',
'Valdoie',
'Valence (Drôme)',
'Valenciennes',
'Valençay',
'Vallabrègues',
'Vallauris',
'Valognes',
'Valserhône',
'Vannes',
'Vanves',
'Varennes',
'Vasteville',
'Vaulx-en-Velin',
'Veauchette',
'Veigné',
'Velaine-en-Haye',
'Vélizy-Villacoublay',
'Vellescot',
'Vendôme',
'Vénissieux',
'Verdun',
'Verfeil',
'Vernaison',
'Vernon',
'Verrières-le-Buisson',
'Versailles',
'Vervins',
'Vesoul',
'Veyrac',
'Vézelay',
'Vichy',
'Vienne (Isère)',
'Vierzon',
'Vieux-Boucau-les-Bains',
'Villainville',
'Villars-les-Dombes',
'Ville-la-Grand',
'Ville-sous-la-Ferté',
'Villebon-sur-Yvette',
'Villechenève',
'Villedieu-les-Poêles',
'Villefranche-de-Rouergue',
'Villefranche-sur-Saône',
'Villejuif',
'Villelaure',
'Villemereuil',
'Villenave d\'Ornon',
'Villeneuve-d\'Ascq',
'Villeneuve-la-Comtesse',
'Villeneuve-le-Roi',
'Villeneuve-Saint-Georges',
'Villeneuve-sur-Lot',
'Villeparisis',
'Villepinte',
'Villepreux',
'Villers-sur-Mer',
'Villeurbanne',
'Vimy',
'Vincennes',
'Vineuil (Loir-et-Cher)',
'Virandeville',
'Vireux-Molhain',
'Vireux-Wallerand',
'Virieu-le-Grand',
'Viroflay',
'Vitry-sur-Seine',
'Vizille',
'Volvic',
'Vouziers',
'Wambrechies',
'Wangenbourg-Engenthal',
'Wattignies',
'Wattrelos',
'Wattwiller',
'Xertigny',
'Y (Somme)',
'Yvetot'
	];
	
	var form = document.getElementById("auto-suggest");
	var input = form.search;
	
	var list = document.createElement("ul");
	list.className = "suggestions";
	list.style.display = "none";

	form.appendChild(list);

	input.onkeyup = function(){
		var txt = this.value;
		if(!txt){
			list.style.display = "none";
			return;
		}
		
		var suggestions = 0;
		var frag = document.createDocumentFragment();
		
		for(var i = 0, c = motsClefs.length; i < c; i++){
			if(new RegExp("^"+txt,"i").test(motsClefs[i])){
				var word = document.createElement("li");
				frag.appendChild(word);
				word.innerHTML = motsClefs[i].replace(new RegExp("^("+txt+")","i"),"<strong>$1</strong>");
				word.mot = motsClefs[i];
				word.onmousedown = function(){					
					input.focus();
					input.value = this.mot;
					list.style.display = "none";
					return false;
				};				
				suggestions++;
			}
		}

		if(suggestions){
			list.innerHTML = "";
			list.appendChild(frag);
			list.style.display = "block";
		}
		else {
			list.style.display = "none";			
		}
	};

	input.onblur = function(){
		list.style.display = "none";
		if(this.value=="")
			this.value = "";}}
			
		
			
			
function lance(){
		var motsClefs1 = [
		'Aast',
		'Abbeville',
		'Ablis',
		'Achères (Yvelines)',
		'Acqueville',
		'Agde',
		'Agel',
		'Agen',
		'Aigues-Mortes',
		'Ainay-le-Château',
		'Aix-en-Provence',
		'Aix-les-Bains',
		'Aizenay',
		'Ajaccio',
		'Albert (Somme)',
		'Albertville',
		'Albi',
		'Albigny-sur-Saône',
		'Alençon',
		'Alfortville',
		'Allemanche-Launay-et-Soyer',
		'Alès',
		'Amboise',
		'Ambérieu-en-Bugey',
		'Amiens',
		'Ancenis',
		'Ancretiéville-Saint-Victor',
		'Andilly',
		'Andilly-en-Bassigny',
		'Anet',
		'Angers',
		'Anglesqueville-l\'Esneval',
		'Angoulême',
		'Annecy',
		'Annemasse',
		'Annonay',
		'Antibes',
		'Antony',
		'Apt',
		'Arcachon',
		'Arconsat',
		'Ardes',
		'Argenteuil',
		'Arles',
		'Armentières',
		'Arras',
		'Arudy',
		'Asnières-sur-Seine',
		'Astaffort',
		'Aubagne',
		'Aubière',
		'Aubrives',
		'Aubusson',
		'Auch',
		'Aulnay-sous-Bois',
		'Auray',
		'Aurillac',
		'Auriol (Bouches-du-Rhône)',
		'Autun',
		'Auvers-sur-Oise',
		'Auxerre',
		'Avignon',
		'Avranches',
		'Avril-sur-Loire',
		'Ax-les-Thermes',
		'Aydat',
		'Aydius',
		'Azay-le-Rideau',
		'Bailleul',
		'Bar-le-Duc',
		'Bar-sur-Aube',
		'Baratier',
		'Barbizon',
		'Barcelonnette',
		'Barneville-Carteret',
		'Basse-Terre',
		'Bastia',
		'Batz-sur-Mer',
		'Bavay',
		'Bayeux',
		'Bayonne',
		'Beaumont-Hague',
		'Beaune',
		'Beauvais',
		'Bégard',
		'Belfort',
		'Bellerive-sur-Allier',
		'Belley',
		'Berck',
		'Bergerac',
		'Bergues',
		'Bernay',
		'Berthen',
		'Besançon',
		'Bessoncourt',
		'Béthune',
		'Beuvry',
		'Beynost',
		'Bèze',
		'Béziers',
		'Biarritz',
		'Billiat',
		'Billom',
		'Billy (Allier)',
		'Binas',
		'Biot (Alpes-Maritimes)',
		'Biscarrosse',
		'Bischwiller',
		'Blagnac',
		'Blain',
		'Blandy-les-Tours',
		'Blois',
		'Bobigny',
		'Boissy-Saint-Léger',
		'Bonchamp-lès-Laval',
		'Bondy',
		'Bonifacio',
		'Bonnat',
		'Bonnières-sur-Seine',
		'Bordeaux',
		'Bordeaux-Saint-Clair',
		'Bort-les-Orgues',
		'Bouère',
		'Bougival',
		'Bouilly (Aube)',
		'Boulogne-Billancourt',
		'Boulogne-sur-Mer',
		'Bourdeau (Savoie)',
		'Bourg-en-Bresse',
		'Bourg-la-Reine',
		'Bourges',
		'Le Bourget',
		'Bourogne',
		'Boussières',
		'Bouvines',
		'Bram',
		'Brancion',
		'Brassempouy',
		'Bray-Dunes',
		'Brebotte',
		'Bressuire',
		'Brest',
		'Breuilpont',
		'Briançon',
		'Bricquebec',
		'Brie-Comte-Robert',
		'Brié-et-Angonnes',
		'Briennon',
		'Brioude',
		'Brive-la-Gaillarde',
		'Bron',
		'Bruguières',
		'Buffard',
		'Bugarach',
		'Busserolles',
		'Cabestany',
		'Cachan',
		'Caen',
		'Cagnes-sur-Mer',
		'Cahors',
		'Cailloux-sur-Fontaines',
		'Calais',
		'Caluire-et-Cuire',
		'Calvi',
		'Camaret-sur-Mer',
		'Cambrai',
		'Cangey',
		'Cannes',
		'Carcassonne',
		'Carentan',
		'Carhaix-Plouguer',
		'Carmaux',
		'Carnac',
		'Carpentras',
		'Carrières-sous-Poissy',
		'Castelginest',
		'Castellane',
		'Castellet-lès-Sausses',
		'Castelmoron-d\'Albret',
		'Castres',
		'Cauchy-à-la-Tour',
		'Caudry',
		'Cayenne',
		'Cébazat',
		'Cergy',
		'Cestas',
		'Chabeuil',
		'Challans',
		'Chalon-sur-Saône',
		'Châlons-en-Champagne',
		'Chambéry',
		'Chamonix',
		'Champagne-au-Mont-d\'Or',
		'Champagney',
		'Champagnier',
		'Champagnole',
		'Champéon',
		'Chantilly',
		'Charbonnières-les-Bains',
		'Charenton-le-Pont',
		'Charleville-Mézières',
		'Charly (métropole de Lyon)',
		'Chartres',
		'Chasse-sur-Rhône',
		'Chassieu',
		'Châteaubriant',
		'Châteaudun',
		'Châteaulin',
		'Châteauneuf-Grasse',
		'Châteauroux',
		'Châtelaillon-Plage',
		'Châtellerault',
		'Chatou',
		'Chaumont (Haute-Marne)',
		'Chaumont-sur-Loire',
		'Chelles',
		'Chemillé-en-Anjou',
		'Chenonceaux',
		'Cherbourg-Octeville',
		'Cherves-Richemont',
		'Chessy (Seine-et-Marne)',
		'Chevreuse',
		'Chinon',
		'Cholet',
		'Château-Chinon',
		'Château-Thierry',
		'Châteaufort (Yvelines)',
		'Châteauneuf-sur-Loire',
		'Châtenay-Malabry',
		'Chédigny',
		'Ciboure',
		'Cierrey',
		'Cigogné',
		'Cintegabelle',
		'Clamart',
		'Clayes',
		'Clermont (Oise)',
		'Clermont-Ferrand',
		'Clichy',
		'Clichy-sous-Bois',
		'Clisson',
		'Cluny',
		'Cognac',
		'Coise',
		'Colleville-Montgomery',
		'Collias',
		'Collioure',
		'Collonges-au-Mont-d\'Or',
		'Colmar',
		'Colombes',
		'Colombier-Saugnieu',
		'Colomiers',
		'Combloux',
		'Combon',
		'Commercy',
		'Compiègne',
		'Conchy-les-Pots',
		'Condom',
		'Conflans-Sainte-Honorine',
		'Confolens',
		'Corbas',
		'Corbon (Orne)',
		'Cordon',
		'Corrèze (commune)',
		'Corte',
		'Courbevoie',
		'Courrières',
		'Courçais',
		'Coutances',
		'Couzon-au-Mont-d\'Or',
		'Craponne',
		'Créteil',
		'Criquetot-l\'Esneval',
		'Crossac',
		'Cublize',
		'Cuges-les-Pins',
		'Curis-au-Mont-d\'Or',
		'Cusset',
		'Dannemarie (Haut-Rhin)',
		'Dardilly',
		'Dax',
		'Deauville',
		'Décines-Charpieu',
		'Delle',
		'Denney',
		'Descartes (Indre-et-Loire)',
		'Deûlémont',
		'Devesset',
		'Die',
		'Dieppe',
		'Digne-les-Bains',
		'Dijon',
		'Dinan',
		'Dol-de-Bretagne',
		'Dole',
		'Dombasle-sur-Meurthe',
		'Domfessel',
		'Domrémy',
		'Douai',
		'Doullens',
		'Dourdan',
		'Douvres-la-Délivrande',
		'Draguignan',
		'Drancy',
		'Dreux',
		'Drusenheim',
		'Dunkerque',
		'Écully',
		'Égletons',
		'Élancourt',
		'Éloise',
		'Épernay',
		'Épinac',
		'Épinal',
		'Épinay-sur-Seine',
		'Épône',
		'Ermenonville',
		'Erquinghem-le-Sec',
		'Erquy',
		'Espelette',
		'Estagel',
		'Étretat',
		'Évian-les-Bains',
		'Évreux',
		'Évry-Courcouronnes',
		'Eysines',
		'Faches-Thumesnil',
		'Falaise (Calvados)',
		'Farnay',
		'Fécamp',
		'Fêche-l\'Église',
		'Felleries',
		'Ferney-Voltaire',
		'Feurs',
		'Feyzin',
		'Figeac',
		'Firminy',
		'Flavigny-sur-Moselle',
		'Fleurieu-sur-Saône',
		'Floirac (Gironde)',
		'Florac',
		'Flottemanville-Hague',
		'Foisches',
		'Foix',
		'Fongueusemare',
		'Fontainebleau',
		'Fontaines-Saint-Martin',
		'Fontaines-sur-Saône',
		'Fontenay-le-Comte',
		'Fontenay-le-Fleury',
		'Fontès',
		'Forbach',
		'Forcalquier',
		'Fort-de-France',
		'Fos-sur-Mer',
		'Fougères',
		'Fouras',
		'Fournels',
		'Frais (Territoire de Belfort)',
		'Francheville (métropole de Lyon)',
		'Freneuse (Yvelines)',
		'Fréjus',
		'Fumay',
		'Gagny',
		'Galgan',
		'Gambsheim',
		'Gap',
		'Garges-lès-Gonesse',
		'Garnat-sur-Engièvre',
		'Gémenos',
		'Genas',
		'Genay (métropole de Lyon)',
		'Gentilly',
		'Gernelle',
		'Gevrey-Chambertin',
		'Gex',
		'Givet',
		'Givors',
		'Gleizé',
		'Gragnague',
		'Grand (Vosges)',
		'Granville',
		'Grasse',
		'Graulhet',
		'Gravelines',
		'Gray',
		'Grenoble',
		'Grigny (métropole de Lyon)',
		'Grosne',
		'Guémené-Penfao',
		'Guérande',
		'Guéret',
		'Guingamp',
		'Guipavas',
		'Guise',
		'Guyancourt',
		'Hagetmau',
		'Haguenau',
		'Hambach',
		'Hargnies',
		'Hazebrouck',
		'Héauville',
		'Helleville',
		'Hénanbihen',
		'Hendaye',
		'Hennebont',
		'Héricourt',
		'Hettange-Grande',
		'Heuqueville',
		'Heyrieux',
		'Hirel',
		'Homécourt',
		'Honfleur',
		'Houilles',
		'Houlgate',
		'Irigny',
		'Issenheim',
		'Issoire',
		'Issou',
		'Issy-les-Moulineaux',
		'Istres',
		'Ivry-sur-Seine',
		'Izernore',
		'Jacou',
		'Jallans',
		'Jargeau',
		'Jonage',
		'Jonzac',
		'Jouy-en-Josas',
		'Jublains',
		'Juvisy-sur-Orge',
		'Kourou',
		'L\'Haÿ-les-Roses',
		'L\'Union',
		'L\'Île-Rousse',
		'La Balme-de-Sillingy',
		'La Baule-Escoublac',
		'La Boisse',
		'La Bonneville-sur-Iton',
		'La Celette',
		'La Chaise-Dieu',
		'La Chapelle-Rablais',
		'La Fare-les-Oliviers',
		'La Féclaz',
		'La Londe-les-Maures',
		'La Motte-Servolex',
		'La Mulatière',
		'La Roche-Guyon',
		'La Roche-sur-Yon',
		'La Rochelle',
		'La Tour-de-Salvagny',
		'La Trimouille',
		'La Trinité-sur-Mer',
		'La Villeneuve-en-Chevrie',
		'La Voulte-sur-Rhône',
		'Labrit',
		'Lagny-sur-Marne',
		'Laguiole',
		'Lalouvesc',
		'Lambersart',
		'Landerneau',
		'Landivisiau',
		'Langeais',
		'Langres',
		'Languidic',
		'Lannilis',
		'Lannion',
		'Lans-en-Vercors',
		'Laon',
		'Lapalisse',
		'Larajasse',
		'Largentière',
		'Laval (Mayenne)',
		'Le Cannet',
		'Le Cellier',
		'Le Chambon-sur-Lignon',
		'Le Chesnay-Rocquencourt',
		'Le Creusot',
		'Le Croisic',
		'Le Drennec',
		'Le Faouët (Morbihan)',
		'Le Havre',
		'Le Mans',
		'Le Mené',
		'Le Mée-sur-Seine',
		'Le Neubourg',
		'Le Pecq',
		'Le Perreux-sur-Marne',
		'Le Perrier',
		'Le Perthus',
		'Le Port (La Réunion)',
		'Le Pouliguen',
		'Le Puy-en-Velay',
		'Le Quesnoy',
		'Le Raincy',
		'Le Rozel',
		'Le Tartre-Gaudran',
		'Le Tilleul',
		'Le Touquet-Paris-Plage',
		'Le Tréport',
		'Le Versoud',
		'Le Vigan (Gard)',
		'Le Vésinet',
		'Lebetain',
		'Lectoure',
		'Lens',
		'Lepuix-Neuf',
		'Les Andelys',
		'Les Baux-de-Provence',
		'Les Clayes-sous-Bois',
		'Les Eyzies-de-Tayac',
		'Les Loges-en-Josas',
		'Les Mathes',
		'Les Mureaux',
		'Les Sables-d\'Olonne',
		'Lesme',
		'Levallois-Perret',
		'Lezigneux',
		'Libourne',
		'Liévin',
		'Lille',
		'Limay',
		'Limeil-Brévannes',
		'Limoges',
		'Limonest',
		'Limoux',
		'Lion-sur-Mer',
		'Lisieux',
		'Lissieu',
		'Loiron-Ruillé',
		'Longwy',
		'Lons-le-Saunier',
		'Lorgues',
		'Lorient',
		'Lorris',
		'Loudéac',
		'Louhossoa',
		'Loulay',
		'Loupia',
		'Lourdes',
		'Luc-sur-Mer',
		'Luçon (Vendée)',
		'Lunel',
		'Lunéville',
		'Lure',
		'Lussault-sur-Loire',
		'Lyon',
		'Mackenheim',
		'Mâcon',
		'Maisons-Alfort',
		'Maisons-Laffitte',
		'Mamoudzou',
		'Mantes-la-Jolie',
		'Mantes-la-Ville',
		'Marcy-l\'Étoile',
		'Marennes-Hiers-Brouage',
		'Mareuil-sur-Cher',
		'Marlhes',
		'Marly-le-Roi',
		'Marquette-lez-Lille',
		'Marray',
		'Marseille',
		'Martigues',
		'Maubeuge',
		'Mauges-sur-Loire',
		'Maurepas (Yvelines)',
		'Mauriac (Cantal)',
		'Mayrac',
		'Mazaugues',
		'Meaux',
		'Melun',
		'Mende',
		'Ménerbes',
		'Menouville',
		'Menton (Alpes-Maritimes)',
		'Mérens-les-Vals',
		'Merlimont',
		'Metz',
		'Meudon',
		'Meyzieu',
		'Millau',
		'Milly-la-Forêt',
		'Mimizan',
		'Mions',
		'Mirande',
		'Mirepoix',
		'Miribel (Ain)',
		'Moissac',
		'Moisson (Yvelines)',
		'Mont-Dauphin',
		'Mont-de-Marsan',
		'Mont-Dore',
		'Montanay',
		'Montargis',
		'Montastruc-la-Conseillère',
		'Montauban',
		'Montbard',
		'Montbéliard',
		'Montceau-les-Mines',
		'Montcy-Notre-Dame',
		'Montebourg',
		'Montélimar',
		'Montesson',
		'Montfort-l\'Amaury',
		'Montivilliers',
		'Montluel',
		'Montluçon',
		'Montmédy',
		'Montpellier',
		'Montpeyroux',
		'Montredon-Labessonnié',
		'Montreuil',
		'Montreuil (Pas-de-Calais)',
		'Montreux-Château',
		'Montreux-Vieux',
		'Montrottier',
		'Montsoreau',
		'Moret-sur-Loing',
		'Morlaix',
		'Morteau',
		'Moulins',
		'Mousseaux-sur-Seine',
		'Moûtiers',
		'Mulhouse',
		'Munster (Moselle)',
		'Murat (Saint-Médard La Rochette)',
		'Muret',
		'Murol',
		'Nancy',
		'Nanterre',
		'Nantes',
		'Nantua',
		'Narbonne',
		'Nérac',
		'Neuf-Berquin',
		'Neuf-Brisach',
		'Neuilly-sur-Marne',
		'Neuilly-sur-Seine',
		'Neuville-sur-Saône',
		'Nevers',
		'Neyron',
		'Nice',
		'Nîmes',
		'Niort',
		'Nogent (Haute-Marne)',
		'Nogent-le-Rotrou',
		'Nogent-sur-Marne',
		'Nogent-sur-Seine',
		'Noirétable',
		'Noisy-le-Roi',
		'Nontron',
		'Nonville (Seine-et-Marne)',
		'Novillard',
		'Noyon',
		'Nozay (Essonne)',
		'Nyons',
		'Octeville-sur-Mer',
		'Onet-le-Château',
		'Opio',
		'Oradour-sur-Glane',
		'Orange (ville)',
		'Orcines',
		'Orcival',
		'Orléans',
		'Orly',
		'Ornans',
		'Osny',
		'Osse-en-Aspe',
		'Oullins',
		'Ounans',
		'Oyonnax',
		'Ozoir-la-Ferrière',
		'Paladru',
		'Pamiers',
		'Papeete',
		'Paray-le-Monial',
		'Parigny-les-Vaux',
		'Paris',
		'Paron',
		'Parthenay',
		'Pau',
		'Paulnay',
		'Périgueux',
		'Péronne',
		'Perpezat',
		'Perpignan',
		'Perros-Guirec',
		'Petit-Croix',
		'Peyrus',
		'Pierre-Bénite',
		'Pierrefiques',
		'Pithiviers',
		'Piégut-Pluviers',
		'Plaisir (Yvelines)',
		'Plateau d\'Hauteville',
		'Plédéliac',
		'Plénée-Jugon',
		'Pléneuf-Val-André',
		'Pleyben',
		'Plomodiern',
		'Plonévez-Porzay',
		'Plouarzel',
		'Plougastel-Daoulas',
		'Pointe-à-Pitre',
		'Poissy',
		'Poitiers',
		'Poleymieux-au-Mont-d\'Or',
		'Pomayrols',
		'Pommeret',
		'Pons',
		'Pont-l\'Évêque',
		'Pont-Aven',
		'Pont-de-Roide',
		'Pont-de-Veyle',
		'Pont-du-Château',
		'Pontarlier',
		'Pontivy',
		'Pontoise',
		'Pornichet',
		'Port-Louis (Morbihan)',
		'Porte des Pierres Dorées',
		'Pralognan-la-Vanoise',
		'Prat',
		'Preuschdorf',
		'Prey',
		'Privas',
		'Provins',
		'Puiseaux',
		'Pujaudran',
		'Pusignan',
		'Quiberon',
		'Quimper',
		'Quincieux',
		'Quissac (Gard)',
		'Rambouillet',
		'Réchésy',
		'Redon',
		'Reims',
		'Rennemoulin',
		'Rennes',
		'Rethel',
		'Retonfey',
		'Ribeauvillé',
		'Rillieux-la-Pape',
		'Riom',
		'Rioz',
		'Ris-Orangis',
		'Risoul',
		'Roanne',
		'Rocamadour',
		'Rochechouart',
		'Rochefort',
		'Rochetaillée-sur-Saône',
		'Rocroi',
		'Rodez',
		'Rognac',
		'Rohrwiller',
		'Roissy-en-France',
		'Rolleboise',
		'Romainville',
		'Romans-sur-Isère',
		'Romenay',
		'Romilly-sur-Seine',
		'Roppe',
		'Roquetoire',
		'Roquevaire',
		'Rosny-sur-Seine',
		'Roubaix',
		'Rouen',
		'Roumare',
		'Roussillon (Isère)',
		'Royan',
		'Rungis',
		'Saint-Agathon',
		'Saint-Amand-Montrond',
		'Saint-André-lez-Lille',
		'Saint-Austremoine',
		'Saint-Bertrand-de-Comminges',
		'Saint-Bonnet-de-Mure',
		'Saint-Brieuc',
		'Saint-Chamas',
		'Saint-Chamond',
		'Saint-Christophe-du-Foc',
		'Saint-Claude-de-Diray',
		'Saint-Cloud',
		'Saint-Cyr-au-Mont-d\'Or',
		'Saint-Cyr-l\'École',
		'Saint-Denis (La Réunion)',
		'Saint-Denis (Seine-Saint-Denis)',
		'Saint-Didier-au-Mont-d\'Or',
		'Saint-Dié-des-Vosges',
		'Saint-Domineuc',
		'Saint-Égrève',
		'Saint-Estèphe',
		'Saint-Étienne',
		'Saint-Étienne-du-Rouvray',
		'Saint-Flour',
		'Saint-Fons',
		'Saint-Gaudens',
		'Saint-Genest-Lerpt',
		'Saint-Genis-Laval',
		'Saint-Genis-les-Ollières',
		'Saint-Germain-au-Mont-d\'Or',
		'Saint-Germain-en-Laye',
		'Saint-Gilles-Croix-de-Vie',
		'Saint-Girons',
		'Saint-Gouéno',
		'Saint-Haon-le-Vieux',
		'Saint-Hilaire-de-Riez',
		'Saint-Hilaire-du-Rosier',
		'Saint-Jacut-du-Mené',
		'Saint-Jean-d\'Angély',
		'Saint-Jean-de-Luz',
		'Saint-Jory',
		'Saint-Julien-en-Genevois',
		'Saint-Just-d\'Avray',
		'Saint-Laurent-du-Pape',
		'Saint-Lyé-la-Forêt',
		'Saint-Léonard-de-Noblat',
		'Saint-Lô',
		'Saint-Malo',
		'Saint-Mandé',
		'Saint-Martin-d\'Ardèche',
		'Saint-Martin-d\'Uriage',
		'Saint-Martin-de-Queyrières',
		'Saint-Martin-de-Ré',
		'Saint-Martin-du-Bec',
		'Saint-Maur-des-Fossés',
		'Saint-Maurice-de-Beynost',
		'Saint-Maurice-l\'Exil',
		'Saint-Maximin-la-Sainte-Baume',
		'Saint-Nazaire',
		'Saint-Nectaire',
		'Saint-Omer (Pas-de-Calais)',
		'Saint-Ouen-sur-Seine',
		'Saint-Paul-lès-Romans',
		'Saint-Pierre (La Réunion)',
		'Saint-Pierre (Martinique)',
		'Saint-Pol-de-Léon',
		'Saint-Priest',
		'Saint-Quentin',
		'Saint-Quentin-en-Yvelines',
		'Saint-Quentin-sur-Indrois',
		'Saint-Rémy-de-Provence',
		'Saint-Romain-au-Mont-d\'Or',
		'Saint-Romain-en-Gal',
		'Saint-Romain-le-Puy',
		'Saint-Rémy-lès-Chevreuse',
		'Saint-Saturnin',
		'Saint-Symphorien-sur-Coise',
		'Saint-Tropez',
		'Saint-Vaast-la-Hougue',
		'Saint-Victor-sur-Rhins',
		'Saint-Vougay',
		'Saint-Zacharie (Var)',
		'Sainte-Croix-Hague',
		'Sainte-Cécile-les-Vignes',
		'Sainte-Eulalie (Gironde)',
		'Sainte-Foy-lès-Lyon',
		'Sainte-Geneviève-des-Bois (Essonne)',
		'Sainte-Luce (Martinique)',
		'Sainte-Marie-de-Ré',
		'Sainte-Mère-Église',
		'Sainte-Pazanne',
		'Saintes',
		'Salazie',
		'Salies-de-Béarn',
		'Samois-sur-Seine',
		'Sanary-sur-Mer',
		'Saran',
		'Sarlat-la-Canéda',
		'Sarreguemines',
		'Sartène',
		'Sartrouville',
		'Sathonay-Camp',
		'Sathonay-Village',
		'Saulieu',
		'Saulnot',
		'Saumur',
		'Sauve',
		'Sauveterre-de-Béarn',
		'Savigny-sur-Orge',
		'Savouges',
		'Sceaux (Hauts-de-Seine)',
		'Schiltigheim',
		'Sebourg',
		'Seclin',
		'Sedan',
		'Semur-en-Vallon',
		'Senlis',
		'Sens (Yonne)',
		'Serres-Castet',
		'Sète',
		'Sevelinges',
		'Sèvres',
		'Sézanne',
		'Sillingy',
		'Siouville-Hague',
		'Sochaux',
		'Soissons',
		'Solaize',
		'Sommières',
		'Sorbiers',
		'Sorgues',
		'Sotteville-lès-Rouen',
		'Soulac-sur-Mer',
		'Strasbourg',
		'Sucy-en-Brie',
		'Sully (Saône-et-Loire)',
		'Sundhouse',
		'Suresnes',
		'Surgères',
		'Talence',
		'Tancua',
		'Tarascon-sur-Ariège',
		'Tarbes',
		'Tassin-la-Demi-Lune',
		'Tavaux',
		'Teurthéville-Hague',
		'Theizé',
		'Thiers (ville)',
		'Thil (Ain)',
		'Thionville',
		'Thomery',
		'Thonon-les-Bains',
		'Thorigny-sur-le-Mignon',
		'Thérouanne',
		'Tigery',
		'Tinténiac',
		'Tomblaine',
		'Tonnay-Charente',
		'Tonnerre (Yonne)',
		'Torcy',
		'Toul',
		'Toulon',
		'Toulouse',
		'Tourcoing',
		'Tournefeuille',
		'Tournon (Savoie)',
		'Tournon-sur-Rhône',
		'Tournus',
		'Tours',
		'Toussus-le-Noble',
		'Tramoyes',
		'Trappes',
		'Trédaniel',
		'Trégomar',
		'Treigny',
		'Treize-Septiers',
		'Trélévern',
		'Tremblay-en-France',
		'Troyes',
		'Tulle',
		'Turretot',
		'Ussel',
		'Uzès',
		'Val d\'Oingt',
		'Valaire',
		'Valbonne',
		'Valdahon',
		'Valdoie',
		'Valence (Drôme)',
		'Valenciennes',
		'Valençay',
		'Vallabrègues',
		'Vallauris',
		'Valognes',
		'Valserhône',
		'Vannes',
		'Vanves',
		'Varennes',
		'Vasteville',
		'Vaulx-en-Velin',
		'Veauchette',
		'Veigné',
		'Velaine-en-Haye',
		'Vélizy-Villacoublay',
		'Vellescot',
		'Vendôme',
		'Vénissieux',
		'Verdun',
		'Verfeil',
		'Vernaison',
		'Vernon',
		'Verrières-le-Buisson',
		'Versailles',
		'Vervins',
		'Vesoul',
		'Veyrac',
		'Vézelay',
		'Vichy',
		'Vienne (Isère)',
		'Vierzon',
		'Vieux-Boucau-les-Bains',
		'Villainville',
		'Villars-les-Dombes',
		'Ville-la-Grand',
		'Ville-sous-la-Ferté',
		'Villebon-sur-Yvette',
		'Villechenève',
		'Villedieu-les-Poêles',
		'Villefranche-de-Rouergue',
		'Villefranche-sur-Saône',
		'Villejuif',
		'Villelaure',
		'Villemereuil',
		'Villenave d\'Ornon',
		'Villeneuve-d\'Ascq',
		'Villeneuve-la-Comtesse',
		'Villeneuve-le-Roi',
		'Villeneuve-Saint-Georges',
		'Villeneuve-sur-Lot',
		'Villeparisis',
		'Villepinte',
		'Villepreux',
		'Villers-sur-Mer',
		'Villeurbanne',
		'Vimy',
		'Vincennes',
		'Vineuil (Loir-et-Cher)',
		'Virandeville',
		'Vireux-Molhain',
		'Vireux-Wallerand',
		'Virieu-le-Grand',
		'Viroflay',
		'Vitry-sur-Seine',
		'Vizille',
		'Volvic',
		'Vouziers',
		'Wambrechies',
		'Wangenbourg-Engenthal',
		'Wattignies',
		'Wattrelos',
		'Wattwiller',
		'Xertigny',
		'Y (Somme)',
		'Yvetot'
	];
	
	var form1 = document.getElementById("auto-suggest1");
	var input1 = form1.search1;
	
	var list1 = document.createElement("ul");
	list1.className = "suggestions1";
	list1.style.display = "none";

	form1.appendChild(list1);

	input1.onkeyup = function(){
		var txt1 = this.value;
		if(!txt1){
			list1.style.display = "none";
			return;
		}
		
		var suggestions1 = 0;
		var frag1 = document.createDocumentFragment();
		
		for(var i1 = 0, c1 = motsClefs1.length; i1 < c1; i1++){
			if(new RegExp("^"+txt1,"i").test(motsClefs1[i1])){
				var word1 = document.createElement("li");
				frag1.appendChild(word1);
				word1.innerHTML = motsClefs1[i1].replace(new RegExp("^("+txt1+")","i"),"<strong>$1</strong>");
				word1.mot = motsClefs1[i1];
				word1.onmousedown = function(){					
					input1.focus();
					input1.value = this.mot;
					list1.style.display = "none";
					return false;
				};				
				suggestions1++;
			}
		}

		if(suggestions1){
			list1.innerHTML = "";
			list1.appendChild(frag1);
			list1.style.display = "block";
		}
		else {
			list1.style.display = "none";			
		}
	};

	input1.onblur = function(){
		list1.style.display = "none";
		if(this.value=="")
			this.value = "";}
			
			
}

//france europe classList.toggle

//document.getElementById("fr").addEventListener("click",change);
function change(){
document.getElementById("fr-bottom").style.backgroundColor="darkblue";
document.getElementById("eu-bottom").style.backgroundColor="#fff";
document.querySelector(".list").innerHTML="<br /><p>Paris à Marseille</p><p>Paris à Lyon</p><p>Train de Paris à Bordeaux</p><p>Train de Paris à Metz</p><p>Marseille à Nice</p><p>Train Nice Paris</p><p>Paris à Perpignan en train</p><p>Lyon à Bordeaux en train</p><p>Train de Paris à Lille</p><p>OUIGO Bordeaux Paris</p><p>Train Paris Strasbourg</p><p>Train de Paris à Deauville </p><p>OUIGO Strasbourg Paris</p><p>OUIGO Lyon Marseille</p><p>Paris à Rouen</p><p>Billets de train</p><p>Horaires des trains</p><p>Trains OUIGO</p><p>Trains SNCF</p><p>Horaires trains SNCB</p>";
}

//document.getElementById("eu").addEventListener("click",change1);
function change1(){
document.getElementById("fr-bottom").style.backgroundColor="#fff";
document.getElementById("eu-bottom").style.backgroundColor="darkblue";
document.querySelector(".list").innerHTML="<br /><p>Paris à Londres</p><p>Londres à Paris</p><p>Paris à Leipzig Hbf</p><p>Paris à Amsterdam</p><p>Paris à Bruxelles</p><p>Paris à Genève</p><p>Paris à Barcelone</p><p>Paris à Le Havre</p><p>Paris à Venise</p><p>Lyon à Genève</p><p>Lille à Bruxelles</p><p>Le Havre à Paris</p><p>Bruxelles à Paris</p><p>Paris à Luxembourg</p><p>Lille à Londres</p><p>Train Italie</p><p>Où aller en train en Europe</p><p>Train Espagne</p><p>Train Belgique</p><p>Train Allemagne</p>";
}

//document.getElementById("Aller").addEventListener("click",type);

//document.getElementById("Retour").addEventListener("click",type);

function type1(){
document.getElementById("Aller").type="date";
document.getElementById("Retour").type="date";
}

//fin france europe classList.toggle





// Get the modal
var modal = document.getElementById("myModal");

// Get the button that opens the modal
/*var btn = document.getElementById("myBtn");*/

var btn = document.querySelector(".menu");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal 

/*btn.onclick = */ function btn1() {
	document.getElementById("myModal").style.display = "block";
}

// When the user clicks on <span> (x), close the modal

/*span.onclick =*/ function span1() {
	document.getElementById("myModal").style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it


window.onclick = function(event) {
  if (event.target == modal) {
	modal.style.display = "none";
  }
}

//fin suggestion

function panier(){
	Swal.fire({
		position: 'bottom-end',
		icon: 'info',
		title: 'votre panier est vide',
		showConfirmButton: false,
		timer : 3600,
	})
}

function erreur(){
	Swal.fire({
		position: 'center',
		icon: 'info',
		title: 'Erreur de saisie la destination ne peux pas etre vide',
		showConfirmButton: false,
		timer : 3600,
	})
}


function erreur1(){
	Swal.fire({
		position: 'center',
		icon: 'info',
		title: 'Les dates saisies ne sont pas valide',
		showConfirmButton: false,
		timer : 3600,
	})
}

function erreur2(){
	Swal.fire({
		position: 'center',
		icon: 'info',
		title: 'Choisissez un nombres de voyageurs',
		showConfirmButton: false,
		timer : 3600,
	})
}



var date=new Date();
var years=date.getFullYear();
var month=date.getMonth();
//mois
if(month<=8){
	month="0"+(month+1);
}else if(month>=9){
	month=month+1
}
//mois
var day=date.getDate();


function search(){
	var date=new Date();
var years=date.getFullYear();
var month=date.getMonth();
//mois
if(month<=8){
	month="0"+(month+1);
}else if(month>=9){
	month=month+1
}
//mois
var day=date.getDate();
if(day<=9){
	day="0"+(day);
}


var depart = document.getElementById("depart");
var arrive = document.getElementById("arrive");
var Aller = document.getElementById("Aller");
var Retour = document.getElementById("Retour");
var select = document.getElementById("select");

if(depart.value !="" && arrive.value !="" && Aller.value==years+"-"+month+"-"+day && Retour.value>=Aller.value && select.value!="0"){ 
	localStorage.setItem("depart",depart.value);
	localStorage.setItem("arrive",arrive.value);
window.location="resultat.html";
}else if(depart.value =="" || arrive.value ==""){
	erreur()
	// css
}else if(Aller.value<years+"-"+month+"-"+day || Retour.value<Aller.value){
	erreur1()
}else if(select.value=="0"){
	erreur2()
}
}

function red(){
	var depart = document.getElementById("depart");
if(depart.value==""){
	depart.style.border="1px solid red";
}else{
	depart.style.border="none";
}
}

function red1(){
	
var arrive = document.getElementById("arrive");

if(arrive.value==""){
	arrive.style.border="1px solid red";
}else{
	arrive.style.border="none";
}
}

function red2(){
	
	var Aller = document.getElementById("Aller");
	
	if(Aller.value==""){
		Aller.style.border="1px solid red";
	}else{
		Aller.style.border="none";
	}
	}

	function red3(){
	
		var Retour = document.getElementById("Retour");
		
		if(Retour.value==""){
			Retour.style.border="1px solid red";
		}else{
			Retour.style.border="none";
		}
		}

		function red4(){
			var select = document.getElementById("select");

			if(select.value==""){
				select.style.border="1px solid red";
			}else{
				select.style.border="none";
			}
			}